# Generated by Django 3.2.25 on 2024-12-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20241219_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
