# Generated by Django 3.2.25 on 2024-12-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_userprofile_losses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='losses',
        ),
    ]
