# Generated by Django 3.2.25 on 2024-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_userprofile_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
    ]
