version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

  web:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app_network


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
     - '8080:8080'
    depends_on:
      - db
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
